package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/uptrace/bun"
)

func collisionCheck(slugs []string, names []string) map[string]string {
	seen := make(map[string]string, len(names))
	collisions := make(map[string]bool)
	for i, name := range names {
		if prev, ok := seen[name]; ok {
			fmt.Fprintf(os.Stderr, "warning: collections %q and %q both produce type name %q; disambiguating\n", prev, slugs[i], name)
			collisions[name] = true
		} else {
			seen[name] = slugs[i]
		}
	}

	overrides := make(map[string]string)
	for i, name := range names {
		if collisions[name] {
			overrides[slugs[i]] = strings.ReplaceAll(slugs[i], "-", "_")
		}
	}
	return overrides
}

// ---------------------------------------------------------------------------
// Stored schema shape
// ---------------------------------------------------------------------------

type storedField struct {
	Name     string   `json:"name"`
	Type     string   `json:"type"`
	Required bool     `json:"required"`
	Options  []string `json:"options,omitempty"`
	MinRole  string   `json:"min_role,omitempty"`
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

func runGenTypes(args []string) {
	var (
		dsn          string
		driver       = "sqlite"
		out          = "./reverb.d.ts"
		excludeAdmin bool
	)

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--db":
			i++
			if i >= len(args) {
				fatalf("gen types: --db requires a value")
			}
			dsn = args[i]
		case "--driver":
			i++
			if i >= len(args) {
				fatalf("gen types: --driver requires a value")
			}
			driver = args[i]
		case "--out":
			i++
			if i >= len(args) {
				fatalf("gen types: --out requires a value")
			}
			out = args[i]
		case "--exclude-admin":
			excludeAdmin = true
		default:
			fatalf("gen types: unknown flag %q", args[i])
		}
	}

	if dsn == "" {
		fatalf("gen types: --db is required")
	}

	db, err := openDB(driver, dsn)
	if err != nil {
		fatalf("gen types: %v", err)
	}
	defer db.Close()

	if err := generateTypes(db, out, excludeAdmin); err != nil {
		fatalf("gen types: %v", err)
	}
}

// ---------------------------------------------------------------------------
// Generation logic
// ---------------------------------------------------------------------------

func generateTypes(db *bun.DB, outPath string, excludeAdmin bool) error {
	ctx := context.Background()

	var collections []struct {
		Slug             string          `bun:"slug"`
		Schema           json.RawMessage `bun:"schema"`
		DeprecatedFields json.RawMessage `bun:"deprecated_fields"`
	}

	err := db.NewSelect().
		TableExpr("reverb_collections").
		Column("slug", "schema", "deprecated_fields").
		Scan(ctx, &collections)
	if err != nil {
		return fmt.Errorf("query collections: %w", err)
	}

	candidateSlugs := make([]string, len(collections))
	candidateNames := make([]string, len(collections))
	for i, c := range collections {
		candidateSlugs[i] = c.Slug
		candidateNames[i] = slugToTypeName(c.Slug)
	}
	overrides := collisionCheck(candidateSlugs, candidateNames)

	var sb strings.Builder

	sb.WriteString("// Auto-generated by reverb gen types. Do not edit manually.\n\n")
	sb.WriteString("export interface Media {\n")
	sb.WriteString("  id: string\n")
	sb.WriteString("  filename: string\n")
	sb.WriteString("  url: string\n")
	sb.WriteString("  mime_type: string\n")
	sb.WriteString("  size: number\n")
	sb.WriteString("  alt: string\n")
	sb.WriteString("  created_at: string\n")
	sb.WriteString("}\n")

	var collectionNames []string

	for i, c := range collections {
		var fields []storedField
		if err := json.Unmarshal(c.Schema, &fields); err != nil {
			return fmt.Errorf("parse schema for %q: %w", c.Slug, err)
		}

		deprecatedSet, err := buildStringSet(c.DeprecatedFields)
		if err != nil {
			return fmt.Errorf("parse deprecated_fields for %q: %w", c.Slug, err)
		}

		typeName := candidateNames[i]
		if override, ok := overrides[c.Slug]; ok {
			typeName = override
		}
		dataTypeName := typeName + "Data"
		collectionNames = append(collectionNames, typeName)

		type fieldSpec struct {
			field    storedField
			optional bool
		}
		var specs []fieldSpec
		for _, f := range fields {
			if deprecatedSet[f.Name] {
				continue
			}
			if f.MinRole == "admin" && excludeAdmin {
				continue
			}
			optional := !f.Required || f.MinRole == "admin"
			specs = append(specs, fieldSpec{field: f, optional: optional})
		}

		sb.WriteByte('\n')
		sb.WriteString("export interface ")
		sb.WriteString(dataTypeName)
		sb.WriteString(" {\n")
		for _, s := range specs {
			tsType := fieldToTSType(s.field)
			if s.optional {
				fmt.Fprintf(&sb, "  %s?: %s\n", s.field.Name, tsType)
			} else {
				fmt.Fprintf(&sb, "  %s: %s\n", s.field.Name, tsType)
			}
		}
		sb.WriteString("}\n")

		sb.WriteByte('\n')
		sb.WriteString("export interface ")
		sb.WriteString(typeName)
		sb.WriteString(" {\n")
		sb.WriteString("  id: string\n")
		sb.WriteString("  status: 'draft' | 'published' | 'archived'\n")
		fmt.Fprintf(&sb, "  data: %s\n", dataTypeName)
		sb.WriteString("  created_at: string\n")
		sb.WriteString("  updated_at: string\n")
		sb.WriteString("}\n")
	}

	if len(collectionNames) > 0 {
		sb.WriteByte('\n')
		sb.WriteString("export type {\n")
		for _, name := range collectionNames {
			fmt.Fprintf(&sb, "  %s,\n", name)
			fmt.Fprintf(&sb, "  %sData,\n", name)
		}
		sb.WriteString("}\n")
	}

	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create output file: %w", err)
	}
	defer f.Close()

	if _, err := f.WriteString(sb.String()); err != nil {
		return fmt.Errorf("write output file: %w", err)
	}

	fmt.Printf("Wrote %s\n", outPath)
	return nil
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func fieldToTSType(f storedField) string {
	switch f.Type {
	case "text", "richtext", "seometa", "date":
		return "string"
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	case "media", "relation":
		return "string | null"
	case "select":
		if len(f.Options) == 0 {
			return "string"
		}
		parts := make([]string, len(f.Options))
		for i, o := range f.Options {
			escaped := strings.ReplaceAll(o, "'", "\\'")
			parts[i] = "'" + escaped + "'"
		}
		return strings.Join(parts, " | ")
	case "json":
		return "Record<string, unknown>"
	default:
		return "unknown"
	}
}

func slugToTypeName(slug string) string {
	parts := strings.FieldsFunc(slug, func(r rune) bool {
		return r == '-' || r == '_'
	})
	var sb strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return sb.String()
}

func buildStringSet(raw json.RawMessage) (map[string]bool, error) {
	if raw == nil {
		return nil, nil
	}
	var names []string
	if err := json.Unmarshal(raw, &names); err != nil {
		return nil, err
	}
	if len(names) == 0 {
		return nil, nil
	}
	set := make(map[string]bool, len(names))
	for _, n := range names {
		set[n] = true
	}
	return set, nil
}
